### ISSUE TITLE
ves_icall_System_AppDomain_ExecuteAssembly failed: -1

### ISSUE THREAD

**Issue by wzq663856650** [BlackMythWukongMods/B1.Mod.Template#1]
我使用了https://github.com/czastack/B1CSharpLoader的源码进行编译，然后将内容按照要求拷贝到运行路径下，然后运行黑神话悟空，在控制台中，它提示了这个错误。该如何处理呢？

**Comment by lxymahatma** [comment]
这个错误如果我没理解错的话应该是CSharpLoader自己炸了，有可能和这个Mod模板关系不大，你重新安装CSharpLoader然后什么mod都不添加还有这个报错吗

**Comment by wzq663856650** [comment]
我已收到，感谢你的来信！

**Comment by wzq663856650** [comment]
我在运行路径中，删除了Mods文件夹，也是不行的，仍然是这个错误。

**Comment by lxymahatma** [comment]
> 我在运行路径中，删除了Mods文件夹，也是不行的，仍然是这个错误。

这样来看应该就和这个mod模板没有关系了，得去CSharpLoader的仓库下面新建一个issue反馈，我这里就先关闭了
